# Generated by Django 5.0.3 on 2024-04-01 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.contact'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='basket', max_length=20),
        ),
    ]
